### ISSUE TITLE
No module named 'custom_components.aqualink.config_flow'

### ISSUE THREAD

**Issue by blysik** [flz/hass-aqualink#2]
This may be related to upgrading to 0.94.0, but I'm not sure.  When I start HA, I see these errors:

```
2019-06-06 08:44:06 ERROR (MainThread) [homeassistant.config_entries] Error importing integration aqualink to set up aqualink config entry: No module named 'custom_components.aqualink.config_flow'
2019-06-06 08:44:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading config flow for integration aqualink: No module named 'custom_components.aqualink.config_flow'
```

and then later on I see this:

```
2019-06-06 08:44:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/config_entries.py", line 681, in _async_create_flow
    integration.get_platform('config_flow')
  File "/usr/src/app/homeassistant/loader.py", line 139, in get_platform
    "{}.{}".format(self.pkg_path, platform_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.aqualink.config_flow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/data_entry_flow.py", line 64, in async_init
    handler, context=context, data=data)
  File "/usr/src/app/homeassistant/config_entries.py", line 686, in _async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
```

This was working previously.  

Any ideas?

**Comment by flz** [comment]
Most likely due to 0.94 upgrade.

I've got a diff locally that I haven't been able to test due to previous limitations (config_flow requiring to modify homeassistant code). I'll try to have a look in the next couple of days.

**Comment by flz** [comment]
Looks like [this commit](https://github.com/home-assistant/home-assistant/commit/1e22c8dacac252e41c152b1b0ce1b9d47ba8c7ec#diff-9e423b96591ab40119af2f0c56ff55cd) solved the (known) issue I was facing. I should be able to test again.

**Comment by flz** [comment]
Should be fixed in master now. Update your checkout and let me know if it's still broken for you.
